### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by AgusWin** [hendra1/OrsenIPB#1]
Hendra saya sudah update tp ada error waktu buka halaman utama. Ada 2 error bedanya 
LINE  NUMBER 61 dan line 72

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: models/content_model.php

Line Number: 61

**Comment by hendra1** [comment]
Pa itu data di databasenya ada yang kurang.
Ambil dari database yg sy udah update.


Untuk Header sama Footernya






On Mon, Jun 15, 2015 at 4:05 PM, AgusWin <notifications@github.com> wrote:

> Hendra saya sudah update tp ada error waktu buka halaman utama. Ada 2
> error bedanya
> LINE NUMBER 61 dan line 72
>
> A PHP Error was encountered
>
> Severity: Notice
>
> Message: Trying to get property of non-object
>
> Filename: models/content_model.php
>
> Line Number: 61
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hendra1/OrsenIPB/issues/1>.
>



-- 
Hendrawan H
