### ISSUE TITLE
Error Tampilan Header dan Footer pada menu Member

### ISSUE THREAD

**Issue by AgusWin** [hendra1/OrsenIPB#3]
Ada message error pada tampilan halaman member sptnya berhubungan dengan footer dan header seperti message di bawah. Bedanya hanya baris 9 dan 15 saja

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: header

Filename: views/base.php

Line Number: 9

**Comment by hendra1** [comment]
sudah update database pa?

On Wed, Jun 17, 2015 at 9:11 AM, AgusWin <notifications@github.com> wrote:

> Ada message error pada tampilan halaman member sptnya berhubungan dengan
> footer dan header seperti message di bawah. Bedanya hanya baris 9 dan 15
> saja
>
> A PHP Error was encountered
>
> Severity: Notice
>
> Message: Undefined variable: header
>
> Filename: views/base.php
>
> Line Number: 9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hendra1/OrsenIPB/issues/3>.
>



-- 
Hendrawan H
